# SPDX-FileCopyrightText: Copyright (c) 2012-2026, Yegor Bugayenko
# SPDX-License-Identifier: MIT

[default.extend-identifiers]
thr = "thr"
frst = "frst"
parms = "parms"

[default.extend-words]
ba = "ba"
ba14 = "ba14"
Dentity = "Dentity"
