# Copyright (c) 2012-2025, Yegor Bugayenko
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met: 1) Redistributions of source code must retain the above
# copyright notice, this list of conditions and the following
# disclaimer. 2) Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following
# disclaimer in the documentation and/or other materials provided
# with the distribution. 3) Neither the name of the s3auth.com nor
# the names of its contributors may be used to endorse or promote
# products derived from this software without specific prior written
# permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
# NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
# THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.
---
# yamllint disable rule:line-length
readers:
  - "urn:github:526301"
docker:
  image: yegor256/rultor-image:1.22.0
install: |
  sudo locale-gen en_US en_US.UTF-8
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
  sudo apt-get install --yes netpbm texlive-fonts-recommended
  sudo gem install pdd
  pdd --source=$(pwd) --verbose --file=/dev/null
assets:
  netrc: yegor256/home#assets/heroku-netrc
  secring.gpg: yegor256/home#assets/secring.gpg
  id_rsa: yegor256/home#assets/heroku-key
  settings.xml: yegor256/home#assets/s3auth/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  id_rsa.pub: yegor256/home#assets/heroku-key.pub
merge:
  script: |-
    mvn help:system clean install --errors -Pqulice --settings ../settings.xml
    mvn clean
deploy:
  script: |-
    mv ../netrc ~/.netrc
    git remote add heroku https://git.heroku.com/s3auth.git
    build=$(git rev-parse --short HEAD)
    chmod 600 ../*.gpg
    sed -i "s/BUILD/${build}/g" s3auth-rest/src/main/resources/log4j.properties
    git add s3auth-rest/src/main/resources/log4j.properties
    sed -i "s/BUILD/${build}/g" s3auth-rest/src/main/resources/META-INF/MANIFEST.MF
    git add s3auth-rest/src/main/resources/META-INF/MANIFEST.MF
    git commit -m 'build number set'
    cp ../settings.xml settings.xml
    mvn clean deploy --errors -Ps3auth -Pqulice --settings settings.xml
    git remote add dokku dokku@www.s3auth.com:s3auth
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git add settings.xml
    git commit -m 'settings.xml' && git push -f heroku $(git symbolic-ref --short HEAD):master && git reset HEAD~1
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 http://www.s3auth.com
    mvn clean deploy --errors -Ps3auth -Pqulice --settings settings.xml -pl :s3auth-relay
    # mvn clean install site-deploy --errors -Psite --settings settings.xml
    mvn clean
