# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    "s3auth-hosts/src/main/resources/META-INF/services/javax.validation.spi.ValidationProvider",
    "s3auth-relay/src/main/resources/META-INF/services/javax.validation.spi.ValidationProvider",
    "s3auth-rest/src/main/resources/META-INF/services/javax.validation.spi.ValidationProvider",
    "s3auth-rest/src/main/resources/images/favicon.ico",
    ".DS_Store",
    ".gitattributes",
    ".gitignore",
    ".pdd",
    "**.json",
    "**.md",
    "**.png",
    "**.svg",
    "**.txt",
    "**.vm",
    "**/.DS_Store",
    "**/.gitignore",
    "**/.pdd",
    "**/*.csv",
    "**/*.jpg",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.png",
    "**/*.svg",
    "**/*.txt",
    "**/*.vm",
    "**/CNAME",
    "**/MANIFEST.MF",
    "**/Procfile",
    "MANIFEST.MF",
    "Procfile",
    "README.md",
    "renovate.json",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2025 Yegor Bugayenko"
SPDX-License-Identifier = "MIT"
