<?xml version="1.0" encoding="UTF-8"?>
<!--
 * SPDX-FileCopyrightText: Copyright (c) 2012-2026, Yegor Bugayenko
 * SPDX-License-Identifier: MIT
-->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3.org/1999/xhtml" version="2.0" exclude-result-prefixes="xs">
  <xsl:output method="xml" omit-xml-declaration="yes"/>
  <xsl:template match="/directory">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"/>
        <link rel="stylesheet" type="text/css" media="all" href="/css/layout.css"/>
        <title>
          <xsl:if test="@prefix = ''">
            <xsl:text>/</xsl:text>
          </xsl:if>
          <xsl:value-of select="@prefix"/>
        </title>
      </head>
      <body>
        <div id="content">
          <p>
            <xsl:text>This is page is auto-generated by </xsl:text>
            <a href="https://www.s3auth.com">
              <xsl:text>s3auth.com</xsl:text>
            </a>
            <xsl:text>.</xsl:text>
          </p>
          <p style="margin-bottom: 2em;">
            <xsl:text>The prefix is: </xsl:text>
            <code>
              <xsl:value-of select="@prefix"/>
            </code>
          </p>
          <table>
            <tr>
              <th>Name</th>
              <th>Size (bytes)</th>
            </tr>
            <xsl:apply-templates select="commonPrefix"/>
            <xsl:apply-templates select="object"/>
          </table>
        </div>
      </body>
    </html>
  </xsl:template>
  <xsl:template match="commonPrefix">
    <tr>
      <td>
        <a>
          <xsl:attribute name="href">
            <xsl:text>/</xsl:text>
            <xsl:value-of select="."/>
            <xsl:text>index.html</xsl:text>
          </xsl:attribute>
          <xsl:value-of select="."/>
        </a>
      </td>
    </tr>
  </xsl:template>
  <xsl:template match="object">
    <tr>
      <td>
        <a>
          <xsl:attribute name="href">
            <xsl:text>/</xsl:text>
            <xsl:value-of select="path"/>
          </xsl:attribute>
          <xsl:value-of select="path"/>
        </a>
      </td>
      <td class="right">
        <xsl:value-of select="size"/>
      </td>
    </tr>
  </xsl:template>
</xsl:stylesheet>
