<?xml version="1.0" encoding="UTF-8"?>
<!--
 * SPDX-FileCopyrightText: Copyright (c) 2012-2026, Yegor Bugayenko
 * SPDX-License-Identifier: MIT
-->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3.org/1999/xhtml" version="2.0" exclude-result-prefixes="xs">
  <xsl:output method="xml" omit-xml-declaration="yes"/>
  <xsl:template match="/versions">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <link rel="stylesheet" type="text/css" media="all" href="/css/layout.css"/>
      </head>
      <body>
        <div id="content">
          <p>
            <xsl:text>This is page is auto-generated by s3auth.com</xsl:text>
          </p>
          <p style="margin-bottom: 2em;">
            <xsl:text>All versions of object: </xsl:text>
            <span class="tt">
              <xsl:value-of select="@object"/>
            </span>
          </p>
          <xsl:apply-templates select="version"/>
        </div>
      </body>
    </html>
  </xsl:template>
  <xsl:template match="version">
    <p>
      <a>
        <xsl:attribute name="href">
          <xsl:text>/</xsl:text>
          <xsl:value-of select="@key"/>
          <xsl:text>?ver=</xsl:text>
          <xsl:value-of select="."/>
        </xsl:attribute>
        <xsl:value-of select="."/>
      </a>
    </p>
  </xsl:template>
</xsl:stylesheet>
