# SPDX-FileCopyrightText: Copyright (c) 2012-2025, Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: bashate
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  bashate:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install bashate
      - run: |
          readarray -t files < <(find . -name '*.sh')
          bashate -i E006,E003 "${files[@]}"
